# Generated by Django 5.2.1 on 2025-05-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расстояние'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Время в пути'),
        ),
    ]
