# Generated by Django 5.2.1 on 2025-05-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0002_rename_delivery_date_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='time',
            new_name='travel_time',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_time',
            field=models.TimeField(default='12:00', verbose_name='Время доставки'),
        ),
    ]
