# Generated by Django 5.2.1 on 2025-05-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0003_rename_time_delivery_travel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время прибытия'),
        ),
    ]
