# Generated by Django 5.2.1 on 2025-05-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0004_delivery_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='distance',
        ),
        migrations.AddField(
            model_name='delivery',
            name='arrival_date',
            field=models.DateField(default='2024-03-19', verbose_name='Дата прибытия'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='departure_date',
            field=models.DateField(default='2024-03-19', verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='departure_time',
            field=models.TimeField(default='12:00', verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='arrival_time',
            field=models.TimeField(default='12:00', verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='travel_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Время в пути (часы)'),
        ),
    ]
