# Generated by Django 5.2.1 on 2025-05-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_server", "0006_customtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="distance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Расстояние"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="file_path",
            field=models.CharField(
                blank=True,
                default=0,
                max_length=255,
                null=True,
                verbose_name="Путь к файлу",
            ),
        ),
    ]
