# Generated by Django 5.2.1 on 2025-05-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0007_delivery_distance_delivery_file_path'),
        ('api_server', '0008_initial_data'),
    ]

    operations = [
    ]
